---
#
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# █▀▀─█▄─▄█─█▀▀─█▀▄─▄▀▄─█───█▀▄─█▄─▄█─▄▀▀▄
# █▀▀─█─▀─█─█▀▀─██▀─█▀█─█───█─█─█─▀─█─█──▄
# ▀▀▀─▀───▀─▀▀▀─▀─▀─▀─▀─▀▀▀─▀▀──▀───▀──▀▀─
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Discord: ❤ | Havana#3558
# Email: EmeraldMC@AstroNetwork.org
# YouTube: https://youtube.com/emeraldassasinplayz
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# ┏━┳┳┳━┳━━┳━┳┓┏┓┏━┳━┳━┳━┳━┓
# ┃┏┫┃┃━╋┓┏┫┃┃┗┛┃┃┃┃┃┃┃┃┃┃━┫
# ┃┗┫┻┣━┃┃┃┃┃┃┃┃┃┃┃┃┏┃┃┃┏╋━┃
# ┗━┻━┻━┛┗┛┗━┻┻┻┛┗━┻┻┻━┻┛┗━┛
# Donwload Latest Version On Poggit!
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# 
? 'ENTITY ID (GO HERE FOR A LIST OF ENTITY IDs: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/EntityIds.php)'
  - - ITEM ID
    - DAMAGE
    - COUNT
  - - ITEM ID
    - DAMAGE
    - COUNT
0:
- - 0
  - 0
  - 0
- - 0
  - 0
  - 0
...
